### ISSUE TITLE
Does not work with Firefox 89

### ISSUE THREAD

**Issue by amirouche** [dzuk-mutant/100r-theme-editor#7]

**Comment by dzuk-mutant** [comment]
I use the latest version of Firefox as my daily driver and I just tested it now with Firefox 90 and it seems to be working fine on my end... It might be worth checking if you have extensions that might be interfering with the function of the app.

If you're still having issues, could you tell me what's specifically going wrong?

**Comment by amirouche** [comment]
Sorry for the sloppy bug report. Dark reader extension was the issue. I disabled dark-reader for your awesome tool !
